docs: Add OpenAPI specification for Curriculum API
agile-learning-institute/mentorHub-curriculum-api pull request #5
Opened 2024-04-18 21:50 UTC by fazzy12

This commit adds the OpenAPI specification YAML file for the Curriculum API. The YAML file includes endpoints, schemas, and descriptions for managing curriculum resources. It follows the OpenAPI 3.0.3 specification and includes paths for adding, updating, and retrieving curriculum information. 

Closes #1

2024-04-18 22:31 UTC, FlatBallFlyer requested changes
I think we also need to add Post patch delete endpoints for curriculum/ID/Topic. I would also appreciate it if you would put anHTML file in the docs folder similar to the one in the person API so that we can publish this swagger

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +      summary: Get a list of all curricula
Likewise there will be no need to get a list of curriculum, so this endpoint can be dropped as well

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +      operationId: getCurriculum
Add a comment here that states if a curriculum does not exist it will be created

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +          type: string
version properties do not be need to be exposed they are going to be deprecated soon

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +      properties:
I don't think review or roadmap need to be required

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +            - celebrated
Does this match the schema for the database, I don't think we need both completed and celebrated, they mean the same thing

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +          type: string
The value should be listed as enum

2024-04-18 22:31 UTC, FlatBallFlyer commented on docs/openapi.yaml
>          apiVersion:
We will strengthen the config schema as you build the API

2024-04-20 17:33 UTC, FlatBallFlyer requested changes
This is looking good, just a few minor changes here, you provided the type for those properties in the schema.

2024-04-20 17:33 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +  /api/config/:
It's a little bit nitpicky but can we move config and health to be the last two in points

2024-04-20 17:33 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +      summary: Update a topic within a curriculum
The patch needs a URL parameter to identify which topic to update

2024-04-20 17:33 UTC, FlatBallFlyer commented on docs/openapi.yaml
> +      summary: Delete a topic from a curriculum
This delete operation also needs topic ID to identify the topic to delete

2024-04-22 10:08 UTC, fazzy12 commented
- Added missing descriptions for 405 responses in the openapi.yaml.
- Rearranged endpoints to position /api/config/ and /api/health/ as the last two points, improving readability.
- Enhanced the patch endpoint to include a URL parameter for specifying the topic to update.
- Modified the delete operation to incorporate a topic ID parameter for precisely identifying the topic to delete."

2024-04-23 15:33 UTC, FlatBallFlyer approved these changes
Draft to be updated when mongo schema is implemented

2024-04-23 15:44 UTC, merged